import type { MarketplaceListing } from "../../../types/MarketplaceListing";

// TODO: replace with `const { data } = await axios.get("/api/marketplace/listings")`
// once the backend endpoint exists. Shape should match MarketplaceListing.
export const dummyMarketplaceListings: MarketplaceListing[] = [
  {
    id: "lst_001",
    title: "Maize soil moisture - Eastern Province, 2025",
    cropType: "Maize",
    region: "Eastern Province",
    price: 120,
    licenseType: "time-limited",
    sellerName: "Mwansa Family Farm",
    sellerRating: 4.6,
    uploadedDate: "2026-06-02",
  },
  {
    id: "lst_004",
    title: "Cassava root growth sensor data - Central Region",
    cropType: "Cassava",
    region: "Central Region",
    price: 60,
    licenseType: "one-time",
    sellerName: "Green Acres Cooperative",
    sellerRating: 4.2,
    uploadedDate: "2026-07-01",
  },
  {
    id: "lst_006",
    title: "Soybean pest incidence log - Copperbelt",
    cropType: "Soybean",
    region: "Copperbelt",
    price: 75,
    licenseType: "research-only",
    sellerName: "Kalunga Farms",
    sellerRating: 4.9,
    uploadedDate: "2026-06-25",
  },
  {
    id: "lst_007",
    title: "Rice paddy nitrogen levels - Lowveld",
    cropType: "Rice",
    region: "Lowveld",
    price: 90,
    licenseType: "one-time",
    sellerName: "Zambezi Valley Farms",
    sellerRating: 4.0,
    uploadedDate: "2026-07-10",
  },
  {
    id: "lst_008",
    title: "Sorghum drought resilience trial - Southern Province",
    cropType: "Sorghum",
    region: "Southern Province",
    price: 180,
    licenseType: "research-only",
    sellerName: "Mwansa Family Farm",
    sellerRating: 4.6,
    uploadedDate: "2026-05-14",
  },
  {
    id: "lst_009",
    title: "Wheat hybrid yield trial - Northern Plains",
    cropType: "Wheat",
    region: "Northern Plains",
    price: 250,
    licenseType: "time-limited",
    sellerName: "Green Acres Cooperative",
    sellerRating: 4.2,
    uploadedDate: "2026-06-18",
  },
];